// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBe8FGOoGcNFnpw6U-SH7V4Fnj6PcSQbuQ',
    appId: '1:375896160020:web:21643bb2323cd7a0ff3401',
    messagingSenderId: '375896160020',
    projectId: 'duscasecamp2025',
    authDomain: 'duscasecamp2025.firebaseapp.com',
    storageBucket: 'duscasecamp2025.firebasestorage.app',
    measurementId: 'G-JJJDMXBJ2R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSUc0nVbBAR_tQf-5rmT4w2hT4yy7xJsI',
    appId: '1:375896160020:android:8a44452b71e01591ff3401',
    messagingSenderId: '375896160020',
    projectId: 'duscasecamp2025',
    storageBucket: 'duscasecamp2025.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvdEmMsWd1NcuhW5zoYUWIq6aBqIVnhiY',
    appId: '1:375896160020:ios:54871726780ecfb8ff3401',
    messagingSenderId: '375896160020',
    projectId: 'duscasecamp2025',
    storageBucket: 'duscasecamp2025.firebasestorage.app',
    iosBundleId: 'com.example.dusCaseCamp',
  );
}
